name: test

on:
  workflow_call:
    inputs:
      pkg_type:
        required: true
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{ inputs.pkg_type }}
